### ISSUE TITLE
Cannot open an OpenAPIv3 YAML file

### ISSUE THREAD

**Issue by unikitty37** [WileyLabs/serve-rapidoc#3]
When I run serve-rapidoc with this command line:

```
$ npx WileyLabs/serve-rapidoc apidocs
```

the file `api_spec.yml` in that folder is not shown; I just see an empty Spec URL bar with a "local JSON file" button.

Clicking that button and loading the `api_spec.yml` directly produces the message `RapiDoc: Unable to read or parse json` in the browser console. As the file isn't JSON, this is not surprising — the README does specifically mention YAML, though.

I'm not sure if this is a RapiDoc issue or a serve-rapidoc issue. The YAML file in question displays correctly with Redoc, so it appears to be valid.

**Comment by BigBlueHat** [comment]
@unikitty37 clearly I missed some notifications. 😕 Could you share the localhost URLs you see? I don't think it's an OpenAPI v3 related issue. Possibly pathing...possibly format. It does work with YAML docs, though, as that's mostly what I use it with typically.

Hard to say with out a few more details...sorry.

Feel free to share those and reopen this if you're interested, though!
